# Generated by Django 4.0.6 on 2022-07-22 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('county', models.CharField(blank=True, choices=[('MOMBASA', 'Mombasa'), ('NAIROBI', 'Nairobi'), ('NAKURU', 'Nakuru'), ('KISUMU', 'Kisumu')], max_length=150)),
                ('estate', models.CharField(blank=True, choices=[('KOMAROCKS', 'Komarocks'), ('UMOJA', 'Umoja'), ('BURUBURU', 'Buruburu'), ('RONGAI', 'Rongai')], max_length=150)),
                ('product_type', models.CharField(blank=True, choices=[('ELECTRONICS', 'Electronics'), ('COMPUTERS', 'Computers'), ('PHONES', 'Phones'), ('LAND', 'Land'), ('HOUSING', 'Housing'), ('VEHICLES', 'Vehicles'), ('JOBS AND JOBS', 'Jobs and Services')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('utilities', models.TextField(blank=True, max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('Photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('Photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('Photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('Photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('Photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('is_published', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
